services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://root:root@mysql/buylist?schema=public
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=buylist
    ports:
      - 3306:3306